In [6]:
import pandas as pd

from scripts.utils import create_df_index_map

# Creating the DataFrame
df = pd.DataFrame({
    'color': ['Red', 'Blue', 'Green', 'Yellow', 'Purple',
              'Orange', 'Pink', 'Brown', 'Black', 'White'],
    'value': [i for i in range(10)]
})

df

    color  value
0     Red      0
1    Blue      1
2   Green      2
3  Yellow      3
4  Purple      4
5  Orange      5
6    Pink      6
7   Brown      7
8   Black      8
9   White      9

In [19]:


selected = df[df['color'].isin(['Red', 'Green', 'Blue'])].index

print(selected)

odd = df[df['value'] % 2 == 0]

mapping = create_df_index_map(odd)

# Map the selected indices to their new positions
mapped_index = [mapping[i] for i in selected if i in mapping]

print(mapped_index)
print(odd)

Index([0, 1, 2], dtype='int64')
[0, 1]
    color  value
0     Red      0
2   Green      2
4  Purple      4
6    Pink      6
8   Black      8

In [11]:
mapping

0    0
1    2
2    4
3    6
4    8
dtype: int64

In [9]:
even

    color  value
1    Blue      1
3  Yellow      3
5  Orange      5
7   Brown      7
9   White      9