In [1]:
import json
import os

import pandas as pd

# Plot the accuracy

dir = '../data/results/experiments/random_forest_experiment_3'

data_df = pd.read_csv(os.path.join(dir, 'data.csv')).drop(columns=['Unnamed: 0'])

with open(os.path.join(dir, 'config.json')) as f:
    config = json.load(f)

data_df

    accuracy    recall  f1_score  mean_cv_score param  n_clusters  run
0   0.992301  0.992494  0.991881       0.982866  rsrq           2    0
1   0.994810  0.993355  0.994373       0.987897  rsrq           2    1
2   0.994210  0.994965  0.993756       0.990055  rsrq           2    2
3   0.997405  0.997381  0.997482       0.979228  rsrq           3    0
4   0.991729  0.990869  0.991439       0.983437  rsrq           3    1
5   0.992353  0.991649  0.991780       0.989802  rsrq           3    2
6   0.990902  0.988110  0.990076       0.976818  rsrq           4    0
7   0.994053  0.992778  0.993602       0.980458  rsrq           4    1
8   0.995752  0.994334  0.995353       0.978734  rsrq           4    2
9   0.994053  0.994649  0.993727       0.990649  rsrq           5    0
10  0.994053  0.991541  0.992173       0.969380  rsrq           5    1
11  0.995773  0.993683  0.994808       0.982246  rsrq           5    2
12  0.989805  0.986967  0.987306       0.985550  rsrq           6    0
13  0.995773  0.994776  0.995433       0.982271  rsrq           6    1
14  0.991955  0.991718  0.991771       0.950897  rsrq           6    2
15  0.977177  0.976818  0.975864       0.956880  rsrq           7    0
16  0.987128  0.986402  0.986618       0.946078  rsrq           7    1
17  0.992235  0.989912  0.991218       0.979277  rsrq           7    2
18  0.992759  0.990977  0.992016       0.969429  rsrq           8    0
19  0.990509  0.986628  0.989032       0.971514  rsrq           8    1
20  0.993109  0.990369  0.991648       0.971570  rsrq           8    2
21  0.987058  0.985986  0.987446       0.957703  rsrq           9    0
22  0.987941  0.984710  0.985483       0.968111  rsrq           9    1
23  0.986722  0.979352  0.980740       0.965145  rsrq           9    2

In [5]:
data_df.groupby('n_clusters')[['accuracy', 'recall', 'f1_score', 'mean_cv_score']].mean().round(3)

            accuracy  recall  f1_score  mean_cv_score
n_clusters
2              0.994   0.994     0.993          0.987
3              0.994   0.993     0.994          0.984
4              0.994   0.992     0.993          0.979
5              0.995   0.993     0.994          0.981
6              0.993   0.991     0.992          0.973
7              0.986   0.984     0.985          0.961
8              0.992   0.989     0.991          0.971
9              0.987   0.983     0.985          0.964